import React from 'react';

// Reuse the types from the dashboard if possible, or redefine
interface NextStep {
  actionItem: string;
  nextSteps: string[];
}

interface Category {
  name: string;
  items: NextStep[];
}

interface DashboardEmailProps {
  categories: Category[];
  userFirstName?: string; // Optional: for personalization
}

export const DashboardEmail: React.FC<Readonly<DashboardEmailProps>> = ({ categories, userFirstName }) => (
  <html lang="en">
    <head>
      <meta charSet="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>Your Action Items Dashboard</title>
      <style>{`
        body {
          font-family: sans-serif;
          line-height: 1.6;
          color: #333;
          margin: 0;
          padding: 0;
          background-color: #f4f4f4;
        }
        .container {
          max-width: 600px;
          margin: 20px auto;
          padding: 20px;
          background-color: #fff;
          border-radius: 8px;
          box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        h1, h2, h3 {
          color: #1a1a1a;
        }
        h1 {
          border-bottom: 1px solid #eee;
          padding-bottom: 10px;
        }
        .category {
          margin-bottom: 20px;
          border: 1px solid #eee;
          border-radius: 4px;
          overflow: hidden; /* Ensures border-radius applies to children */
        }
        .category-header {
          background-color: #eef2ff; /* Light blue background */
          padding: 10px 15px;
          font-size: 1.1em;
          font-weight: bold;
          color: #4338ca; /* Indigo color */
          border-bottom: 1px solid #dee2e6;
        }
        .item-table {
          width: 100%;
          border-collapse: collapse;
        }
        .item-table th, .item-table td {
          text-align: left;
          padding: 12px 15px;
          border-bottom: 1px solid #eee;
        }
        .item-table th {
          background-color: #f8f9fa;
          font-weight: 600;
        }
        .item-table tr:last-child td {
          border-bottom: none;
        }
        ul {
          padding-left: 20px;
          margin-top: 5px;
          margin-bottom: 5px;
        }
        li {
          margin-bottom: 4px;
        }
        .footer {
          margin-top: 20px;
          text-align: center;
          font-size: 0.9em;
          color: #777;
        }
      `}</style>
    </head>
    <body>
      <div className="container">
        <h1>📋 Your Action Items Dashboard</h1>
        {userFirstName && <p>Hi {userFirstName},</p>}
        <p>Here is a summary of your current action items:</p>

        {categories.length > 0 ? (
          categories.map((category, index) => (
            <div key={index} className="category">
              <div className="category-header">{category.name}</div>
              <table className="item-table">
                <thead>
                  <tr>
                    <th>Action Item</th>
                    <th>Next Steps</th>
                  </tr>
                </thead>
                <tbody>
                  {category.items.map((item, itemIndex) => (
                    <tr key={itemIndex}>
                      <td>{item.actionItem}</td>
                      <td>
                        {item.nextSteps.length > 0 ? (
                          <ul>
                            {item.nextSteps.map((step, stepIndex) => (
                              <li key={stepIndex}>{step}</li>
                            ))}
                          </ul>
                        ) : (
                          <span>No specific next steps listed.</span>
                        )}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          ))
        ) : (
          <p>You currently have no action items logged.</p>
        )}

        <div className="footer">
          <p>Generated by Voice Notes App</p>
        </div>
      </div>
    </body>
  </html>
); 